version: "3.7"
services:
  gatsby-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-blog
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
    # tty: true
    # stdin_open: true
    command: yarn dev
